# Generated by Django 5.0.3 on 2024-04-04 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0002_smsverification"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="smsverification",
            name="expires_in",
        ),
        migrations.AddField(
            model_name="smsverification",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
