# Generated by Django 5.0.3 on 2024-04-04 16:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bot", "0003_remove_smsverification_expires_in_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="verified",
            field=models.BooleanField(default=False),
        ),
    ]
